### ISSUE TITLE
Support for unsafe-eval?

### ISSUE THREAD

**Issue by STRML** [MatAtBread/nodent-runtime#3]
The call to `new Function()` makes the runtime unusable with a strict CSP.

It's pretty difficult to figure out what `processIncludes` actually does, but for now we take the generated code & export that.

**Comment by MatAtBread** [comment]
It bundles together files (like a poor man's browserify or webpack) so the runtime can be identified a single function, suitable for serialisation.

Can you be more specific about what the issue is and how you might avoid it?

**Comment by STRML** [comment]
The issue is using this in-browser with a content security policy that
doesn't include "unsafe-eval".

I'm not sure why this technique is needed, the require statement is still
in the package, making it necessary to still use a bundler.

**Comment by MatAtBread** [comment]
Ah, ok, so you're using browserify or webpack before shipping to the browser? In that case, your current technique is probably the best solution. I have thought about adding a build step to generate the "bundled" runtime so you simply require it, e.g require('nodent-runtime/dist') but it's not happened.

Feel free to make a request or generate a PR. As long as it's backwards-compatible (and likely to be forward-compatible) I'll probably go with it

The initial use-case (and hence legacy requirement) was to be able to call $asynbind.toString() and get the entire runtime delivered (as a single function), which is why it now builds that as source and calls new Function().

**Comment by MatAtBread** [comment]
Of course, the other solution is to `use nodent-promises {"noRuntime":true}`, then you don't need to require anything

**Comment by STRML** [comment]
_nevermind, misread_

Going to work on a dist solution as a PR.

**Comment by STRML** [comment]
Got it - thanks. I'll see about a simple build so I can get us back on
mainline.

**Comment by matAtWork** [comment]
Closed (i hope) by 1f4704c106d64f3ed571a29d2a71ed2fffbffd9d
